In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#vorremmo leggere tutta la tabella
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

df = pd.read_csv("LabDelSole.csv", encoding = "latin1")
print("DataFrame")
df.head()

DataFrame

,tipologia,modello,ore impiegate,prezzo,peso,design mio,perline,rimaste,regalate,passaparola aut 23,passaparola inv 23,passaparola prim 24,passaparola est 24,passaparola aut 24,passaparola inv 24,passaparola prim 25,passaparola est 25,passaparola aut 25,passaparola inv 25,passaparola prim 26,passaparola est 26,mercatino est 24,mercatino inv 24,mercatino aut 25,mercatino prim 26,mercatino est 26
0,ciondolo,albero,8.0,50,NaN,True,True,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,ciondolo,albero semplice,5.0,35,7.35,True,False,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,orecchini,spirali con raggi,2.0,20,2.80,True,True,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,orecchini,pesci,1.0,15,2.90,False,False,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,2.0
4,orecchini,sole-luna,1.0,15,1.90,True,True,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
print("INFO")
df.info()
print("\nDESCRIBE")
df.describe()

INFO
<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipologia            84 non-null     str
 1   modello              84 non-null     str
 2   ore impiegate        84 non-null     float64
 3   prezzo               84 non-null     int64
 4   peso                 47 non-null     float64
 5   design mio           84 non-null     bool
 6   perline              84 non-null     bool
 7   rimaste              45 non-null     float64
 8   regalate             22 non-null     float64
 9   passaparola aut 23   5 non-null      float64
 10  passaparola inv 23   7 non-null      float64
 11  passaparola prim 24  5 non-null      float64
 12  passaparola est 24   9 non-null      float64
 13  passaparola aut 24   7 non-null      float64
 14  passaparola inv 24   8 non-null      float64
 15  passaparola prim 25  6 non-null      float64
 16  passaparola est 25   7 non-null      float64
 17  passaparola aut 25   4 non-null      float64
 18  passaparola inv 25   7 non-null      float64
 19  passaparola prim 26  4 non-null      float64
 20  passaparola est 26   5 non-null      float64
 21  mercatino est 24     9 non-null      float64
 22  mercatino inv 24     5 non-null      float64
 23  mercatino aut 25     4 non-null      float64
 24  mercatino prim 26    7 non-null      float64
 25  mercatino est 26     15 non-null     float64
dtypes: bool(2), float64(21), int64(1), str(2)
memory usage: 17.6 KB

DESCRIBE

,ore impiegate,prezzo,peso,rimaste,regalate,passaparola aut 23,passaparola inv 23,passaparola prim 24,passaparola est 24,passaparola aut 24,passaparola inv 24,passaparola prim 25,passaparola est 25,passaparola aut 25,passaparola inv 25,passaparola prim 26,passaparola est 26,mercatino est 24,mercatino inv 24,mercatino aut 25,mercatino prim 26,mercatino est 26
count,84.000000,84.000000,47.000000,45.000000,22.000000,5.0,7.0,5.0,9.0,7.0,8.000000,6.0,7.0,4.00,7.000000,4.00,5.0,9.000000,5.0,4.0,7.0,15.000000
mean,3.216667,28.511905,5.281915,1.111111,1.090909,1.0,1.0,1.0,1.0,1.0,1.125000,1.0,1.0,1.25,1.142857,1.25,1.0,1.111111,1.0,1.0,1.0,1.066667
std,2.026620,10.887701,3.815350,0.317821,0.294245,0.0,0.0,0.0,0.0,0.0,0.353553,0.0,0.0,0.50,0.377964,0.50,0.0,0.333333,0.0,0.0,0.0,0.258199
min,0.200000,5.000000,0.400000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.00,1.000000,1.00,1.0,1.000000,1.0,1.0,1.0,1.000000
25%,2.000000,20.000000,2.500000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.00,1.000000,1.00,1.0,1.000000,1.0,1.0,1.0,1.000000
50%,3.000000,25.000000,3.800000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.00,1.000000,1.00,1.0,1.000000,1.0,1.0,1.0,1.000000
75%,4.000000,35.000000,7.450000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.25,1.000000,1.25,1.0,1.000000,1.0,1.0,1.0,1.000000
max,12.000000,60.000000,17.800000,2.000000,2.000000,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,2.00,2.000000,2.00,1.0,2.000000,1.0,1.0,1.0,2.000000

In [3]:
# qui voglio riempire tutti nan con zeri tranne la colonna del peso (peso 0 è diverso da non pesato)
salvapeso = df["peso"]
df = df.fillna(0)
df["peso"] = salvapeso

#df.drop(columns=["modello"], inplace=True)

In [4]:
nuove_col = []

for col in df.columns:
    if "passaparola" in col:
        nuove_col.append(("passaparola", col.replace("passaparola ", "")))
    elif "mercatino" in col:
        nuove_col.append(("mercatino", col.replace("mercatino ", "")))
    else:
        nuove_col.append(("info", col))

df.columns = pd.MultiIndex.from_tuples(nuove_col)

In [5]:
df_venduti=df["passaparola"].add(df["mercatino"], fill_value=0)
df_venduti.columns = pd.MultiIndex.from_product([["venduti"], df_venduti.columns])
df = pd.concat([df, df_venduti], axis=1)
df.head()

        info                                                                   \
   tipologia            modello ore impiegate prezzo  peso design mio perline
0   ciondolo             albero           8.0     50   NaN       True    True
1   ciondolo    albero semplice           5.0     35  7.35       True   False
2  orecchini  spirali con raggi           2.0     20  2.80       True    True
3  orecchini              pesci           1.0     15  2.90      False   False
4  orecchini          sole-luna           1.0     15  1.90       True    True

                   passaparola                                              \
  rimaste regalate      aut 23 inv 23 prim 24 est 24 aut 24 inv 24 prim 25
0     0.0      1.0         0.0    1.0     0.0    0.0    0.0    0.0     0.0
1     1.0      0.0         0.0    0.0     0.0    0.0    0.0    0.0     0.0
2     0.0      1.0         0.0    0.0     0.0    1.0    0.0    0.0     0.0
3     1.0      2.0         0.0    0.0     0.0    0.0    0.0    0.0     0.0
4     1.0      1.0         1.0    0.0     0.0    0.0    0.0    0.0     0.0

                                      mercatino                               \
  est 25 aut 25 inv 25 prim 26 est 26    est 24 inv 24 aut 25 prim 26 est 26
0    0.0    0.0    1.0     0.0    0.0       0.0    0.0    0.0     0.0    1.0
1    0.0    0.0    0.0     0.0    0.0       0.0    0.0    0.0     0.0    0.0
2    0.0    0.0    0.0     0.0    0.0       0.0    0.0    0.0     1.0    0.0
3    0.0    0.0    1.0     1.0    0.0       0.0    0.0    0.0     1.0    2.0
4    0.0    0.0    0.0     0.0    0.0       0.0    0.0    0.0     0.0    0.0

  venduti                                                                  \
   aut 23 aut 24 aut 25 est 24 est 25 est 26 inv 23 inv 24 inv 25 prim 24
0     0.0    0.0    0.0    0.0    0.0    1.0    1.0    0.0    1.0     0.0
1     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0
2     0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0     0.0
3     0.0    0.0    0.0    0.0    0.0    2.0    0.0    0.0    1.0     0.0
4     1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0


  prim 25 prim 26
0     0.0     0.0
1     0.0     0.0
2     0.0     1.0
3     0.0     2.0
4     0.0     0.0